production:
  WHITE_LIST:
    - "http://dunamis-analyst-app-2022-beta.s3-website.ap-northeast-2.amazonaws.com"
    - "http://dunamis-analyst-app-2022.s3-website.ap-northeast-2.amazonaws.com"
    - "http://dunamis-analyst-app-prop-beta.s3-website.ap-northeast-2.amazonaws.com"
    - "http://dunamis-analyst-app-prop.s3-website.ap-northeast-2.amazonaws.com"
    - "http://dunamis-analyst-app-fund-beta.s3-website.ap-northeast-2.amazonaws.com"
    - "http://dunamis-analyst-app-fund.s3-website.ap-northeast-2.amazonaws.com"
    - "http://dunamis-crypto-portfolio-app.s3-website.ap-northeast-2.amazonaws.com"
development:
  WHITE_LIST:
    - "http://dunamis-analyst-sandbox.s3-website.ap-northeast-2.amazonaws.com"
    - "http://dunamis-analyst-app-prop-sandbox.s3-website.ap-northeast-2.amazonaws.com"
    - "http://dunamis-analyst-app-fund-sandbox.s3-website.ap-northeast-2.amazonaws.com"
    - "http://dunamis-crypto-portfolio-app-sandbox.s3-website.ap-northeast-2.amazonaws.com"
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "http://localhost:3002"
